# docker compose -f kafka.yml up -d
# docker compose -f kafka.yml build --no-cache
version: '3.9'

services:
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:3.6.3
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - internal-network
  kafka:
    container_name: kafka
    image: bitnami/kafka:3.2.1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - internal-network
    depends_on:
      - zookeeper

  app-delivery:
    container_name: delivery
    build: ../application/delivery
    ports:
      - 8081:8081
    networks:
      - internal-network
    depends_on:
      - kafka
  app-logging:
    container_name: logging
    build: ../application/logging
    ports:
      - 8082:8082
    networks:
      - internal-network
    depends_on:
      - kafka
  app-message:
    container_name: message
    build: ../application/message
    ports:
      - 8083:8083
    networks:
      - internal-network
    depends_on:
      - kafka
  app-order:
    container_name: order
    build: ../application/order
    ports:
      - 8084:8084
    networks:
      - internal-network
    depends_on:
      - kafka

networks:
  internal-network:
    driver: bridge

