# docker compose -f kafka.yml up -d
# docker compose -f kafka.yml build --no-cache
version: '3.9'

services:
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:3.6.3
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - internal-network
  kafka:
    container_name: kafka
    image: bitnami/kafka:3.2.1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - internal-network
    depends_on:
      - zookeeper
  kafdrop:
    container_name: kafdrop
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    networks:
      - internal-network
    depends_on:
      - kafka
  influxdb:
    image: influxdb:1.8
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
  grafana:
    image: grafana/grafana:latest
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/
  k6:
    image: grafana/k6:latest
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./samples:/scripts

  app-delivery:
    container_name: delivery
    build: ../application/delivery
    ports:
      - 8081:8081
    networks:
      - internal-network
    depends_on:
      - kafka
  app-logging:
    container_name: logging
    build: ../application/logging
    ports:
      - 8082:8082
    networks:
      - internal-network
    depends_on:
      - kafka
  app-message:
    container_name: message
    build: ../application/message
    ports:
      - 8083:8083
    networks:
      - internal-network
    depends_on:
      - kafka
  app-order:
    container_name: order
    build: ../application/order
    ports:
      - 8084:8084
    networks:
      - internal-network
    depends_on:
      - kafka

networks:
  internal-network:
    driver: bridge
  k6:
    driver: bridge
  grafana:
    driver: bridge

