# docker compose -f kafka-only.yml up -d
# docker compose -f kafka-only.yml build --no-cache
version: '3.9'
name: kafka
services:
  zookeeper:
    image: bitnami/zookeeper:3.6.3
    container_name: zookeeper
    platform: linux/amd64
    ports:
      - "2181:2181"
  kafka:
    image: bitnami/zookeeper:3.6.3
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    #    volumes:
    #      - /var/run/docker.sock
    depends_on:
      - zookeeper