spring:
  h2:
    console:
      enabled: false
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: com.asterlker.common.domain.config.JpaNamingStrategy
    properties:
      hibernate:
        show-sql: true
        default_batch_fetch_size: 100
    open-in-view: false
---
spring.config.activate.on-profile: local
spring:
  h2:
    console:
      enabled: true
#  defer-datasource-initialization: true
#  sql:
#    init:
#      data-locations: classpath:sql/**
---
spring.config.activate.on-profile: dev
